# Generated by Django 3.0 on 2020-01-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date_uploaded',
            field=models.DateTimeField(blank=True),
        ),
    ]
