# Generated by Django 3.0 on 2020-01-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0003_auto_20200120_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
