# Generated by Django 3.0 on 2020-01-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0005_remove_price_date_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
